### PR TITLE
use only switch description if available

### PR DESCRIPTION
**Pull request by orcema**
the switch description is not visible in HA du to the rule number taking away the visible space. 
If you agree i would suggest to display the description if available and use the current display rule othervise

Screenshot 2021-11-09 at 07 06 55

### CODE REVIEW

**Comment by travisghansen** [comment]
Thanks! I have some pretty massive changes queued up for the main branch…let me get those merged and then we’ll discuss this one.

**Comment by nagyrobi** [comment]
+1 for this, I was about to ask for the same thing.

**Comment by orcema** [comment]
> +1 for this, I was about to ask for the same thing.

in the mean time until the PR is integrated you could temporary install my repo.
Go to custom integration

Screenshot 2021-11-14 at 19 44 30

then add the git url:

`https://github.com/orcema/hass-pfsense`

and then you can add the integration:

Screenshot 2021-11-14 at 19 46 49

my repo is updated (fetch upstream) on a daily basis, thus always inline with the main repo `https://github.com/travisghansen/hass-pfsense.git`

**Comment by nagyrobi** [comment]
Thanks but I'm in progress testing something else in the `next` branch.

**Comment by travisghansen** [comment]
I think main has everything from next at this point.

**Pull request closed without merging**
